package com.model.bean;
// Generated 4/06/2014 04:27:28 PM by Hibernate Tools 3.6.0



/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer id;
     private String rut;
     private String nombre;
     private int fijo;
     private int celular;
     private String email;

    public Persona() {
    }

    public Persona(String rut, String nombre, int fijo, int celular, String email) {
       this.rut = rut;
       this.nombre = nombre;
       this.fijo = fijo;
       this.celular = celular;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRut() {
        return this.rut;
    }
    
    public void setRut(String rut) {
        this.rut = rut;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getFijo() {
        return this.fijo;
    }
    
    public void setFijo(int fijo) {
        this.fijo = fijo;
    }
    public int getCelular() {
        return this.celular;
    }
    
    public void setCelular(int celular) {
        this.celular = celular;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


